stages:
  - build
  - test

ok_to_submit:
  image: ${TESTING_DOCKER_IMAGE}
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: always
    - when: never
  script:
    - curl -Ls ${TESTING_BASE_URL}/${TESTING_SECRET}/check_submission.txt | python3 - ${TESTING_BASE_URL}/${TESTING_SECRET}/cse13s-fall22.toml check

runtests:
  image: ${TESTING_DOCKER_IMAGE}
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "api"
      when: always
    - when: never
  script:
    - curl -Ls ${TESTING_BASE_URL}/${TESTING_SECRET}/check_submission.txt | python3 - ${TESTING_BASE_URL}/${TESTING_SECRET}/cse13s-fall22.toml test test
